"""Upgrade real older workspaces (SQL dumps produced by those releases' init_db).

The fixtures were generated by running ``init_db`` from origin/main (v27) and
from the protocol-negotiation branch (v28), plus one model event and one
conversation, so these tests exercise the real old schemas instead of a
current database with columns dropped.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from app.db import DB_SCHEMA_VERSION, init_db
from app.persistence.upgrades import migration_name

FIXTURES = Path(__file__).parent / "fixtures"


def load(version: int, tmp_path: Path) -> Path:
    path = tmp_path / "careerloop.db"
    with sqlite3.connect(path) as conn:
        conn.executescript((FIXTURES / f"workspace_v{version}.sql").read_text(encoding="utf-8"))
    return path


def columns(conn: sqlite3.Connection, table: str) -> set[str]:
    return {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}


@pytest.mark.parametrize("version", [27, 28])
def test_real_old_workspace_upgrades_to_current(tmp_path, version):
    path = load(version, tmp_path)
    with sqlite3.connect(path) as conn:
        assert conn.execute("SELECT MAX(version) FROM schema_migrations").fetchone()[0] == version
        before_tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        before_counts = {table: conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] for table in before_tables}

    init_db(path)

    with sqlite3.connect(path) as conn:
        assert conn.execute("PRAGMA integrity_check").fetchone()[0] == "ok"
        assert conn.execute("PRAGMA foreign_key_check").fetchall() == []
        migrations = dict(conn.execute("SELECT version, name FROM schema_migrations"))
        assert migrations[version] == "independent_library"
        assert migrations[DB_SCHEMA_VERSION] == migration_name(DB_SCHEMA_VERSION) == "litellm_model_layer"
        # No existing row is lost (schema_migrations gains one row).
        for table, count in before_counts.items():
            expected = count + 1 if table == "schema_migrations" else count
            assert conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] == expected, table
        assert conn.execute("SELECT title FROM conversations WHERE title = 'fixture-conversation'").fetchone()
        event = conn.execute("SELECT model_name, cost_usd, backend, fallback_from_profile_id FROM model_service_events").fetchone()
        assert event == ("gpt-4o", None, "", "")
        assert {"detected_protocol"} <= columns(conn, "model_connections")
        assert {"reasoning_effort"} <= columns(conn, "model_profiles")
        assert {"cost_usd", "backend", "fallback_from_profile_id"} <= columns(conn, "model_service_events")
        tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert {"model_fallback_policy", "model_capability_records"} <= tables

    backup = tmp_path / ".upgrade-backups" / f"before-schema-v{DB_SCHEMA_VERSION}" / "careerloop.db"
    with sqlite3.connect(backup) as conn:
        assert conn.execute("SELECT MAX(version) FROM schema_migrations").fetchone()[0] == version

    init_db(path)  # idempotent
    with sqlite3.connect(path) as conn:
        assert conn.execute("SELECT COUNT(*) FROM schema_migrations WHERE version = ?", (DB_SCHEMA_VERSION,)).fetchone()[0] == 1


def test_fresh_workspace_records_named_current_migration(tmp_path):
    path = tmp_path / "careerloop.db"
    init_db(path)
    with sqlite3.connect(path) as conn:
        assert conn.execute("SELECT version, name FROM schema_migrations").fetchall() == [
            (DB_SCHEMA_VERSION, "litellm_model_layer"),
        ]
